version: '3.8'
name: hackat3am
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.app
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - hackat3am
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:3001
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - hackat3am
networks:
  hackat3am:
    name: hackat3am
