version: '3.8'
name: hackat3am
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.app
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/api
      - /api/node_modules
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://localhost:3001
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
